apiVersion: v1
data:
  body-size: "0"
  # Change redirect code to 301 as 308 is not understood by social media bots
  http-redirect-code: "301"
  # We can't include subdomains for canonical.com
  # It only seems possible to set this globally
  hsts-include-subdomains: "false"
  map-hash-bucket-size: "128"
  proxy-body-size: "0"
  proxy-buffer-size: "8k"
  proxy-buffers: "4 8k"
  enable-brotli: "true"
kind: ConfigMap
metadata:
  name: nginx-configuration
