kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: staging-canonical-com
  namespace: staging
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: staging.canonical.com
    spec:
      containers:
        - name: staging-canonical-com
          image: prod-comms.docker-registry.canonical.com/canonical.com:latest
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: global-envvars
                optional: true
            
            - configMapRef:
                name: proxy-config
                optional: true
            
          
          env:
            - name: SENTRY_DSN
              value: https://aedc7a57f0bc4d22bf7c0b6d63c3e1bb@sentry.is.canonical.com//14
          
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
