## Important!
## This file is just an example to follow the structure of a yaml chart
## It contains all the possibles values and modifications for the defined templates
## If you want to check the values of each project check /sites

name: canonical-com
domain: canonical.com
port: 80

production:
  ## (Optional)
  namespace: production

  ## (Optional)
  replicas: 5

  container:
    image: prod-comms.docker-registry.canonical.com/canonical.com
    tag: latest

  ## It will load the proxy ConfigMap in the Deployment
  ## Take a look at /configmaps/proxy-config.yaml
  useSquid: true

  ## Sentry DSN
  ## (Optional)
  sentryDsn: https://aedc7a57f0bc4d22bf7c0b6d63c3e1bb@sentry.is.canonical.com//14

  ## HTTP path for the readiness probe GET request
  ##
  ## Default: /_status/check
  ## (Optional)
  readinessPath: /_status/check

  ingress:
    nginxConfig:  |
      if ($host != 'canonical.com' ) {
        rewrite ^ https://canonical.com$request_uri? permanent;
      }
      more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
