---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ data.get('name') or get_site_name() }}
  namespace: {{ namespace }}
spec:
  replicas: {{ data.replicas }}
  selector:
    matchLabels:
      app: {{ data.get('app_name') or domain }}
  template:
    metadata:
      labels:
        app: {{ data.get('app_name') or domain }}
    spec:
      containers:
        - name: {{ data.get('name') or get_site_name() }}
          image: {{ data.image }}:{{ tag | default("latest", true) }}

          ports:
            - name: http
              containerPort: {{ data.containerPort | default(80) }}

          env:
            - name: TALISKER_NETWORKS
              value: 10.0.0.0/8

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ data.get('secretKey') or get_site_name() }}
                  name: secret-keys

            {%- if data.useProxy is not defined or data.useProxy != False %}
            {% macro proxy_settings() %}{% include 'proxy-settings.yaml' %}{% endmacro %}
            {{ proxy_settings() | indent(12) }}
            {%- endif %}

            {%- if "env" in data %}
            {%- for env in data.env %}
            - name: {{ env.name }}
              {%- if "value" in env %}
              value: "{{ env.value }}"
              {%- endif %}

              {%- if "secretKeyRef" in env %}
              valueFrom:
                secretKeyRef:
                  key: {{ env.secretKeyRef.key }}
                  name: {{ env.secretKeyRef.name }}
              {%- endif %}

              {%- if "configMapKeyRef" in env %}
              valueFrom:
                configMapKeyRef:
                  key: {{ env.configMapKeyRef.key }}
                  name: {{ env.configMapKeyRef.name }}
              {%- endif %}
            {%- endfor %}
            {%- endif %}

          {%- if data.readinessPath is not defined or data.readinessPath != false %}
          readinessProbe:
            httpGet:
              path: {{ data.readinessPath | default("/_status/check") }}
              port: 80
            periodSeconds: 5
            timeoutSeconds: 3
          {%- endif %}

          resources:
            limits:
              memory: {{ data.memoryLimit | default("256Mi") }}
