---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: staging-cloud-init-io
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: staging-cloud-init-io-tls
    hosts:
    - staging.cloud-init.io
  rules:
  - host: staging.cloud-init.io
    http:
      paths:
      - path: /
        backend:
          serviceName: cloud-init-io
          servicePort: 80

---
